config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }
  devise_for :employees, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }
  devise_scope :employee do
    post "employees/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "employees_search" => "searches#employees_search"
    get "articles_search" => "searches#articles_search"
    get "groups_search" => "searches#groups_search"
    get "department_search" => "searches#department_search"
    get "tag_search" => "searches#tag_search"

    resources :activities, only: [:index] do
      collection do
        delete "destroy_all" => "activities#destroy_all"
      end
    end
    resources :employees, only: [:index, :show, :edit, :update]
    resources :articles do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :groups do
      resource :group_members, only: [:create, :destroy]
      resources :notices, only: [:new, :create, :show, :destroy]
    end
  end

  namespace :admin do
    get "employees_search" => "searches#employees_search"
    get "articles_search" => "searches#articles_search"
    get "department_search" => "searches#department_search"
    get "tag_search" => "searches#tag_search"

    resources :employees, only: [:index, :show, :edit, :update]
    resources :articles, only: [:index, :show] do
      resources :comments, only: [:destroy]
    end
    resources :departments, only: [:create, :index, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord

  has_many :employees, -> { order(created_at: :desc) }


  validates :name, presence: true, uniqueness: true

end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_action :set_department, only: [:edit, :update]

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_back fallback_location: admin_employees_path, notice: "部署の登録が完了しました"
    else
      @departments = Department.all
      render :index
    end
  end

  def index
    @department = Department.new
    @departments = Department.all
  end

  def edit
  end

  def update
    @department.update(department_params) ? (redirect_to admin_departments_path, notice: "部署の変更が完了しました") : (render :edit)
  end


  private


    def department_params
      params.require(:department).permit(:name)
    end

    def set_department
      @department = Department.find(params[:id])
    end


end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/views/admin/departments/_department_form.html.erb
<% if department.id %>
  <%= form_with model: department, url: admin_department_path, method: :patch do |f| %>
    <%= render "admin/shared/error_messages", resource: f.object %>
    <div class="form form--center">
      <p class="form__item"><%= f.text_field :name, autofocus: true, placeholder: "部署名を入力", class: "form-text" %></p>
      <%= f.submit "登録", class: "rounded-btn" %>
    </div>
  <% end %>
<% else %>
  <%= form_with model: department, url: admin_departments_path, method: :post do |f| %>
    <%= render "admin/shared/error_messages", resource: f.object %>
    <div class="form form--center">
      <p class="form__item"><%= f.text_field :name, autofocus: true, placeholder: "部署名を入力", class: "form-text" %></p>
      <%= f.submit "登録", class: "rounded-btn" %>
    </div>
    <% end %>
<% end %>

app/views/admin/departments/_department_search_list.html.erb
<% if admin_signed_in? %>
  <%= link_to admin_department_search_path(department_id: department.id), class: "horizontal-department-list__item" do %>
    <li class="department-name"><%= department.name %></li>
  <% end %>
<% else %>
  <%= link_to department_search_path(department_id: department.id), class: "horizontal-department-list__item" do %>
    <li class="department-name"><%= department.name %></li>
  <% end %>
<% end %>

app/views/admin/departments/edit.html.erb
<div class="form-group">
  <%= render "department_form", department: @department %>
</div>

app/views/admin/departments/index.html.erb
<div class="form-group">
  <%= render "department_form", department: @department %>
  <ul class="vertical-department-list">
      <h2 class="vertical-department-list__item">部署一覧</h2>
    <% @departments.each do |department| %>
      <li class="vertical-department-list__item">
        <div class="vertical-department__name">
          <%= department.name %>
        </div>
        <%= link_to "編集", edit_admin_department_path(department), class: "rounded-btn rounded-btn--s" %>
      </li>
    <% end %>
  </ul>
</div>