config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }
  devise_for :employees, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }
  devise_scope :employee do
    post "employees/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "employees_search" => "searches#employees_search"
    get "articles_search" => "searches#articles_search"
    get "groups_search" => "searches#groups_search"
    get "department_search" => "searches#department_search"
    get "tag_search" => "searches#tag_search"

    resources :activities, only: [:index] do
      collection do
        delete "destroy_all" => "activities#destroy_all"
      end
    end
    resources :employees, only: [:index, :show, :edit, :update]
    resources :articles do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :groups do
      resource :group_members, only: [:create, :destroy]
      resources :notices, only: [:new, :create, :show, :destroy]
    end
  end

  namespace :admin do
    get "employees_search" => "searches#employees_search"
    get "articles_search" => "searches#articles_search"
    get "department_search" => "searches#department_search"
    get "tag_search" => "searches#tag_search"

    resources :employees, only: [:index, :show, :edit, :update]
    resources :articles, only: [:index, :show] do
      resources :comments, only: [:destroy]
    end
    resources :departments, only: [:create, :index, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  belongs_to :department
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_members, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :articles, -> { includes(:tags, :favorites, :comments) }, dependent: :destroy
  has_many :groups, -> { includes(:creater, :group_members) }, through: :group_members, source: :group
  has_many :favorite_articles, -> { includes(:tags, :favorites, :comments) }, through: :favorites, source: :article


  has_one_attached :profile_image


  with_options presence: do
    validates :last_name
    validates :first_name
    validates :last_name_furigana, format: { with: /\A[ァ-ヶー－]+\z/, message: "は全角カタカナで入力してください" }
    validates :first_name_furigana, format: { with: /\A[ァ-ヶー－]+\z/, message: "は全角カタカナで入力してください" }
    validates :birthdate
    validates :prefecture
  end


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def full_name = "#{last_name} #{first_name}"

  def full_name_furigana = "#{last_name_furigana} #{first_name_furigana}"

  def self.search(keyword)

    self.where(
      "last_name LIKE ? or first_name LIKE ? or last_name_furigana LIKE ? or first_name_furigana LIKE ?",
      "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%",
    )
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) { |employee|
      employee.password = SecureRandom.urlsafe_base64
      employee.last_name = "ゲスト"
      employee.first_name = "ユーザー"
      employee.last_name_furigana = "ゲスト"
      employee.first_name_furigana = "ユーザー"
      employee.department = Department.find_by(id: 1)
      employee.birthdate = "1999-11-11"
      employee.prefecture = "東京都"
    }
  end

  def guest_employee?
    email == GUEST_USER_EMAIL
  end

  def active_for_authentication? = super && is_active

  def inactive_message = is_active ? super : :account_inactive

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update]

  def index
    @employees = Employee.includes(:department).page(params[:page])
    @departments = Department.all
  end

  def show
  end

  def edit
  end

  def update
    @employee.update(employee_params) ? (redirect_to admin_employee_path(@employee), notice: "社員情報の変更が完了しました") : (render :edit)
  end

  private

    def employee_params
      params.require(:employee).permit(
        :last_name,
        :first_name,
        :last_name_furigana,
        :first_name_furigana,
        :birthdate,
        :prefecture,
        :department_id,
        :introduction,
        :email,
        :is_active
      )
    end

    def set_employee
      @employee = Employee.find(params[:id])
    end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/views/admin/employees/_employee_record.html.erb
<tr class="tbody__list">
  <td class="td"><%= employee.id %></td>
  <td class="td">
    <%= link_to admin_employee_path(employee) do %>
      <p class="employee-name"><%= employee.full_name %></p>
    <% end %>
  </td>
  <td class="td"><%= employee.department.name %></td>
  <td class="td"><%= employee.email %></td>
  <td class="td">
    <% if employee.is_active %>
      <span class="status">有効</span>
    <% else %>
      <span class="status--non-actived">停止</span>
    <% end %>
  </td>
</tr>

app/views/admin/employees/_employee_record_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>社員ID</th>
      <th>社員名</th>
      <th>所属部署</th>
      <th>メールアドレス</th>
      <th>社員ステータス</th>
    </tr>
  </thead>
  <tbody class="tbody employee_record_group">
    <%= render partial: "admin/employees/employee_record", collection: employees, as: "employee" %>
  </tbody>
</table>
<%= paginate employees %>

app/views/admin/employees/_search_group.html.erb
<div class="search-group">
  <div class="search-group__item">
    <div class="search">
      <%= render "public/searches/search_form", keyword: keyword %>
    </div>
  </div>
  <div class="search-group__item">
    <h3>部署検索</h3>
    <ul class="horizontal-department-list ">
      <%= render partial: "admin/departments/department_search_list", collection: departments, as: "department" %>
    </ul>
  </div>
</div>

app/views/admin/employees/edit.html.erb
<div class="form-group">
  <%= form_with model: @employee, url: admin_employee_path  do |f| %>
    <%= render "admin/shared/error_messages", resource: f.object %>
    <div class="form">
      <p class="form__item">社員ID</p>
      <p class="form__item"><%= @employee.id %></p>
    </div>
    <div class="form">
      <p class="form__item"><%= f.label "氏名" %></p>
      <p class="form__item"><%= f.text_field :last_name, autofocus: true, class: "form-text" %></p>
      <p class="form__item"><%= f.text_field :first_name, class: "form-text" %></p>
    </div>
    <div class="form">
      <p class="form__item"><%= f.label "氏名(カナ)" %></p>
      <p class="form__item"><%= f.text_field :last_name_furigana, class: "form-text" %></p>
      <p class="form__item"><%= f.text_field :first_name_furigana, class: "form-text" %></p>
    </div>
    <div class="form">
      <p class="form__item"><%= f.label :birthdate, "生年月日" %></p>
      <p class="form__item"><%= f.date_field :birthdate, class: "form-text" %></p>
    </div>
    <div class="form">
      <p class="form__item"><%= f.label :prefecture, "出身地" %></p>
      <p class="form__item"><%= f.text_field :prefecture, class: "form-text" %></p>
    </div>
    <div class="form">
      <p class="form__item"><%= f.label :department_id, "部署" %></p>
      <p class="form__item"><%= f.collection_select :department_id, Department.all, :id, :name, {include_blank: "部署を選択してください"}, {class: "form-text"} %></p>
    </div>
    <div class="form">
      <p class="form__item"><%= f.label :email, "メールアドレス" %></p>
      <p class="form__item"><%= f.email_field :email, class: "form-text" %></p>
    </div>
    <div class="form">
      <p class="form__item">社員ステータス</p>
      <p class="form__item">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "有効", {value: :true} %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "停止", {value: :false} %>
      </p>
    </div>
    <div class="form-group__btn">
      <%= f.submit "登録情報を変更", class: "rounded-btn" %>
    </div>
  <% end %>
</div>

app/views/admin/employees/index.html.erb
<%= render "admin/employees/search_group", keyword: @keyword, departments: @departments %>

<table class="table">
  <thead>
    <tr>
      <th>社員ID</th>
      <th>社員名</th>
      <th>所属部署</th>
      <th>メールアドレス</th>
      <th>社員ステータス</th>
    </tr>
  </thead>
  <tbody class="tbody employee_record_group">
    <%= render partial: "admin/employees/employee_record", collection: @employees, as: "employee" %>
  </tbody>
</table>
<%= paginate @employees %>

app/views/admin/employees/show.html.erb
<div class="form-group">
  <div class="form">
    <p class="form__item">社員ID</p>
    <p class="form__item"><%= @employee.id %></p>
  </div>
  <div class="form">
    <p class="form__item">名前</p>
    <p class="form__item"><%= @employee.full_name %></p>
  </div>
  <div class="form">
    <p class="form__item">名前(フリガナ)</p>
    <p class="form__item"><%= @employee.full_name_furigana %></p>
  </div>
  <div class="form">
    <p class="form__item">生年月日</p>
    <p class="form__item"><%= @employee.birthdate %></p>
  </div>
  <div class="form">
    <p class="form__item">出身地</p>
    <p class="form__item"><%= @employee.prefecture %></p>
  </div>
  <div class="form">
    <p class="form__item">部署</p>
    <p class="form__item"><%= @employee.department.name %></p>
  </div>
  <div class="form">
    <p class="form__item">メールアドレス</p>
    <p class="form__item"><%= @employee.email %></p>
  </div>
  <div class="form">
    <p class="form__item">社員ステータス</p>
    <p class="form__item">
      <% if @employee.is_active %>
        <span class="status">有効</span>
      <% else %>
        <span class="status--non-actived">停止</span>
      <% end %>  
    </p>
  </div>
</div>
<%= link_to "社員情報を変更", edit_admin_employee_path(@employee), class: "rounded-btn" %>

            