config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }
  devise_for :employees, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }
  devise_scope :employee do
    post "employees/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "employees_search" => "searches#employees_search"
    get "articles_search" => "searches#articles_search"
    get "groups_search" => "searches#groups_search"
    get "department_search" => "searches#department_search"
    get "tag_search" => "searches#tag_search"

    resources :activities, only: [:index] do
      collection do
        delete "destroy_all" => "activities#destroy_all"
      end
    end
    resources :employees, only: [:index, :show, :edit, :update]
    resources :articles do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :groups do
      resource :group_members, only: [:create, :destroy]
      resources :notices, only: [:new, :create, :show, :destroy]
    end
  end

  namespace :admin do
    get "employees_search" => "searches#employees_search"
    get "articles_search" => "searches#articles_search"
    get "department_search" => "searches#department_search"
    get "tag_search" => "searches#tag_search"

    resources :employees, only: [:index, :show, :edit, :update]
    resources :articles, only: [:index, :show] do
      resources :comments, only: [:destroy]
    end
    resources :departments, only: [:create, :index, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer__inner">
    <small class="footer-copyright">@ 2023 HisashiSaeki</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header__inner">
    <%= link_to root_path, class: "header__logo" do %>
      <h2 class="logo">OfficeCircle</h2>
    <% end %>
    <nav>
      <ul class="nav-list">
        <% if employee_signed_in? %>
          <li class="nav-list__item">
            <%= link_to activities_path do %>
              <% if current_employee.activities.where(checked: false).exists? %>
                <i class="fa-sharp fa-solid fa-bell fa-beat" style="color: #f2ee7d;"></i>
              <% else %>
                <i class="fa-sharp fa-solid fa-bell"></i>
              <% end %>
              通知一覧
            <% end %>
          </li>
          <li class="nav-list__item"><%= link_to "マイページへ", employee_path(current_employee) %></li>
          <li class="nav-list__item"><%= link_to "新規投稿", new_article_path %></li>
          <li class="nav-list__item"><%= link_to "社員一覧", employees_path %></li>
          <li class="nav-list__item"><%= link_to "投稿一覧", articles_path %></li>
          <li class="nav-list__item"><%= link_to "グループ一覧", groups_path %></li>
          <li class="nav-list__item"><%= link_to "ログアウト", destroy_employee_session_path, method: :delete %></li>
        <% elsif admin_signed_in? %>
          <li class="nav-list__item"><%= link_to "社員一覧", admin_employees_path %></li>
          <li class="nav-list__item"><%= link_to "投稿一覧", admin_articles_path %></li>
          <li class="nav-list__item"><%= link_to "部署一覧", admin_departments_path %></li>
          <li class="nav-list__item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
        <% else %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OfficeCircle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4a7905e8fa.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class="content">
      <div class="flash-message">
        <% flash.each do |message_type, message| %>
          <div class="<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
        <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>